### ISSUE TITLE
>= and <= support?

### ISSUE THREAD

**Issue by peterkhayes** [Automattic/expect.js#108]
Hi - when comparing two integers, it would be nice to be able to test greater-than-or-equal-to.  I know you can do expect(a).to.not.be.lessThan(b), but the intention is less clear in this case, and it seems like an easy fix.

**Comment by EvanHahn** [comment]
This project wasn't being maintained so I forked this project and made [expecting.js](https://github.com/EvanHahn/expecting.js), which supports what you're asking for:

``` js
expect(1).to.be.greaterThanOrEqualTo(2)
expect(1).to.be.greaterThanOrEqualTo(1)

expect(2).to.be.lessThanOrEqualTo(3)
expect(2).to.be.lessThanOrEqualTo(2)
```

I realize it's over a year late, but I hope this can help.
